#!/bin/bash
# Install the PB Court monitor as a macOS launchd user agent.
#
# Idempotent: re-running uninstalls the previous version first.
# Prompts for Gmail credentials only if the env file doesn't already exist.

set -euo pipefail

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
REPO_DIR="$( cd "$SCRIPT_DIR/.." && pwd )"
LABEL="com.user.pbcourt-monitor"
PLIST_TPL="$SCRIPT_DIR/$LABEL.plist.tpl"
PLIST_DST="$HOME/Library/LaunchAgents/$LABEL.plist"
ENV_DIR="$HOME/.config/pbcourt-monitor"
ENV_FILE="$ENV_DIR/env"

# --- pre-flight checks ---

if [ "$(uname)" != "Darwin" ]; then
    echo "ERROR: launchd is macOS-only (you are on $(uname))" >&2
    exit 1
fi
if [ ! -f "$PLIST_TPL" ]; then
    echo "ERROR: plist template not found at $PLIST_TPL" >&2
    exit 1
fi
if [ ! -x "$REPO_DIR/.venv/bin/python" ]; then
    echo "ERROR: venv not set up at $REPO_DIR/.venv" >&2
    echo "  Run: cd $REPO_DIR && python3 -m venv .venv && .venv/bin/pip install -r requirements.txt && .venv/bin/python -m playwright install chromium" >&2
    exit 1
fi
if ! command -v "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome" >/dev/null 2>&1 \
    && [ ! -x "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome" ]; then
    echo "WARNING: Google Chrome not found at /Applications/Google Chrome.app" >&2
    echo "  The scraper uses channel='chrome' which requires the system Chrome." >&2
    echo "  Install from https://www.google.com/chrome/ and re-run this script." >&2
fi

# --- env file ---

mkdir -p "$ENV_DIR"
chmod 700 "$ENV_DIR"

if [ ! -f "$ENV_FILE" ]; then
    echo
    echo "Setting up Gmail credentials at $ENV_FILE"
    echo "(These match the GMAIL_USER / GMAIL_APP_PASSWORD / EMAIL_TO secrets"
    echo " you already have configured in GitHub Actions.)"
    echo
    read -r -p "GMAIL_USER (your Gmail address): " gmail_user
    read -r -s -p "GMAIL_APP_PASSWORD (16-char app password, hidden): " gmail_pass
    echo
    read -r -p "EMAIL_TO (where alerts go; leave blank to default to GMAIL_USER): " email_to
    cat >"$ENV_FILE" <<EOF
# Generated by scripts/install_launchd.sh — chmod 600
export GMAIL_USER="$gmail_user"
export GMAIL_APP_PASSWORD="$gmail_pass"
export EMAIL_TO="$email_to"
EOF
    chmod 600 "$ENV_FILE"
    echo "✓ wrote $ENV_FILE (chmod 600)"
else
    echo "✓ env file already exists at $ENV_FILE (leaving alone)"
fi

# --- plist generation ---

mkdir -p "$HOME/Library/LaunchAgents"
sed -e "s|__REPO_DIR__|$REPO_DIR|g" -e "s|__HOME__|$HOME|g" \
    "$PLIST_TPL" >"$PLIST_DST"
chmod 644 "$PLIST_DST"
echo "✓ wrote $PLIST_DST"

# --- load with launchctl ---

# Unload any existing instance (ignore errors — bootout fails if not loaded).
launchctl bootout "gui/$UID/$LABEL" 2>/dev/null || true

if launchctl bootstrap "gui/$UID" "$PLIST_DST"; then
    echo "✓ launchctl bootstrap OK"
else
    echo "ERROR: launchctl bootstrap failed" >&2
    exit 1
fi

echo
echo "--- status ---"
launchctl print "gui/$UID/$LABEL" 2>&1 | grep -E "(state|program|run interval|last exit)" | head -10 || true
echo
echo "✓ Installed. Job runs hourly at :47."
echo "  Log:  ~/Library/Logs/pbcourt-monitor.log"
echo "  Test now:  $SCRIPT_DIR/pbcourt_run.sh   (runs once, writes to log)"
echo "  Uninstall: $SCRIPT_DIR/uninstall_launchd.sh"
